name: Test Suite

on:
  pull_request:
    branches: [develop]
  push:
    branches: [develop]

jobs:
  frontend-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: |
          cd 01.frontend
          npm ci --legacy-peer-deps

      - name: Run tests
        run: |
          cd 01.frontend
          npm test -- --watchAll=false
